driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
  - name: centos-6.7
    driver:
      image: centos:6
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts
  - name: centos-7.2
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts openssl
  - name: ubuntu-14.04
    driver:
      image: ubuntu-upstart:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: debian-7
    driver:
      image: debian:7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release procps -y
  - name: debian-8
    driver:
      image: debian:8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release procps -y


suites:
  - name: default
    run_list:
      - recipe[rabbitmq::default]
  - name: default-use-distro-version
    run_list:
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        use_distro_version: true
    excludes: ["centos-6.7", "centos-7.2"]
  - name: default-force-yes
    run_list:
      - recipe[rabbitmq::default]
    attributes:
           apt:
             confd:
               assume_yes: true
               force-yes: true
    excludes: ["centos-6.7", "centos-7.2"]
  - name: default-force-yes-false
    run_list:
      - recipe[rabbitmq::default]
    attributes:
           apt:
             confd:
               assume_yes: false
               force-yes: false
    excludes: ["centos-6.7", "centos-7.2"]
