Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "erlang::default"
    chef.add_recipe "rabbitmq::default"

    chef.json = {
      "erlang" => {
        "install_method": "esl",
        "esl": {
          "version": "1:20.2.2"
        }
      },
      "rabbitmq" => {
        "version" => "3.7.3"
      }
    }
  end
end
